name: Lint PR title
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  semantic-pr:
    uses: WillBoosterLab/reusable-workflows/.github/workflows/semantic-pr.yml@main
