name: Test
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/docs/**'
  push:
    branches:
      - main
      - wbfy
    paths-ignore:
      - '**.md'
      - '**/docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: WillBooster/reusable-workflows/.github/workflows/test.yml@main
    with:
      runs_on: '["macos-latest"]'
    secrets:
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
